version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: BestellApp_DB
    restart: unless-stopped
    env_file: .env
    ports:
      - "7777:5432"
    volumes:
      - ../init:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  adminer:
    image: adminer
    container_name: app-adminer
    restart: unless-stopped
    ports:
      - "6666:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
